### ISSUE TITLE
request to https://openweathermap.org/current

### ISSUE THREAD

**Issue by jwszolek** [smart-storm/storm-api-monitor#1]
Parse request from openeathermap.org : http://samples.openweathermap.org/data/2.5/weather?lat=35&lon=139&appid=b6907d289e10d714a6e88b30761fae22

get information about temp or other value.

**Comment by opiechow** [comment]
Seems resolved with: https://github.com/smart-storm/storm-api-monitor/commit/deb57ba1221765b2674ff49c14a32d46c378cec4
