### ISSUE TITLE
Can we move it to the configuration file

### ISSUE THREAD

**Issue by jwszolek** [smart-storm/storm-api-monitor#6]
https://github.com/smart-storm/storm-api-monitor/blob/a6ba3a4c0e833bbbeac59de802c16808d8e9665f/json_translator/src/main/java/com/smartstorm/jsonSender.java#L25

**Comment by opiechow** [comment]
Seems resolved with: https://github.com/smart-storm/storm-api-monitor/commit/deb57ba1221765b2674ff49c14a32d46c378cec4
